webtalk_init -webtalk_dir C:/Users/prana/OneDrive/Documents/GitHub/AES128_Verilog/complete_verilog/complete_verilog.sim/sim_1/behav/xsim/xsim.dir/t_mem_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 24 18:27:00 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "06944bd3-9bcf-4a79-8a4e-03e6830ecdd3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fde8bae71b2645e98736ea56fa62f43e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1382 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6512_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3910969292 -regid "" -xml C:/Users/prana/OneDrive/Documents/GitHub/AES128_Verilog/complete_verilog/complete_verilog.sim/sim_1/behav/xsim/xsim.dir/t_mem_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/prana/OneDrive/Documents/GitHub/AES128_Verilog/complete_verilog/complete_verilog.sim/sim_1/behav/xsim/xsim.dir/t_mem_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/prana/OneDrive/Documents/GitHub/AES128_Verilog/complete_verilog/complete_verilog.sim/sim_1/behav/xsim/xsim.dir/t_mem_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
